/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author Lara Vazquez Dorna
 */
public class Dlg_Chat extends javax.swing.JDialog {

    public Socket sock;
    public BufferedReader reader;
    public PrintWriter writer;
    public String nick;

    public Dlg_Chat(Inicio parent, boolean modal) {
        super(parent, modal);
        sock = parent.sock;
        reader = parent.reader;
        writer = parent.writer;
        nick = parent.nick;
        initComponents();

        Thread thread = new Thread(new ReadThread());
        thread.start();
    }

    public class ReadThread implements Runnable {

        @Override
        public void run() {
            String stream;

            try {
                while ((stream = reader.readLine()) != null) {

                    //comprueba si es un comando
                    if (stream.startsWith("/")) {
                        String cmd = stream.substring(1, stream.indexOf(' '));
                        String content = stream.substring(stream.indexOf(' ') + 1);
                        //si el comando es usuarios lo separa para mostrar en la lista de usuarios
                        if (cmd.equalsIgnoreCase("users")) {
                            DefaultListModel listModel = new DefaultListModel();
                            String[] users = content.split(",");
                            for (int i = 0; i < users.length; i++) {
                                listModel.add(i, users[i]);
                            }
                            listaUsuarios.setModel(listModel);
                        }
                    } else {
                        chat.append(stream + "\n");
                    }

                }
            } catch (Exception ex) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList();
        imput = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextArea();
        b_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(listaUsuarios);

        imput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imputActionPerformed(evt);
            }
        });

        chat.setColumns(20);
        chat.setRows(5);
        jScrollPane2.setViewportView(chat);

        b_Salir.setText("Salir");
        b_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imput)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_Salir)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 97, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(imput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(b_Salir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imputActionPerformed
        //escribe en el buffer
        String msg = imput.getText();
        writer.println(msg);
        chat.append("[" + nick + "]: " + msg + "\n");
        writer.flush(); // flushes the buffer
        imput.setText("");
    }//GEN-LAST:event_imputActionPerformed

    private void b_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_SalirActionPerformed
        // TODO add your handling code here:
        writer.println("/logout ");
        writer.flush();
        this.dispose();
    }//GEN-LAST:event_b_SalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Salir;
    private javax.swing.JTextArea chat;
    private javax.swing.JTextField imput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaUsuarios;
    // End of variables declaration//GEN-END:variables
}
